name: plants
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.11.1
  cupertino_icons: ^0.1.3
  moor: ^3.3.1
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  sqlite3_flutter_libs: ^0.2.0
  path_provider: ^1.6.18
  path: ^1.7.0
  json_annotation: ^3.0.1
  rxdart: ^0.24.1
  url_launcher: ^5.5.0
  image_picker: ^0.6.7+6
  freezed_annotation: ^0.12.0
  animate_do: ^1.7.2
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator:
  json_serializable: ^3.2.0
  build_runner: ^1.10.1
  flutter_launcher_icons: ^0.7.3
  freezed: ^0.12.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Plants
      fonts:
      - asset: fonts/Plants.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
