/// Flutter icons Plants
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Plants
///      fonts:
///       - asset: fonts/Plants.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Plants {
  Plants._();

  static const _kFontFam = 'Plants';
  static const _kFontPkg = null;

  static const IconData plant = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
